import time

from navigation.motion_commands import MotionCommand
from validation.navigation_metrics import NavigationMetrics


class PerformanceMonitor:
    """Measures camera, detection, tag, and command timing performance."""

    def __init__(self, fps_window_sec: float = 1.0) -> None:
        """
        Create a performance monitor.

        Args:
            fps_window_sec: Time window used for FPS calculations.
        """
        self.metrics = NavigationMetrics()
        self.fps_window_sec = fps_window_sec
        self._camera_window_start = time.monotonic()
        self._detection_window_start = time.monotonic()
        self._camera_frame_count = 0
        self._detection_frame_count = 0
        self._current_detection_time: float | None = None
        self._command_generated_time: float | None = None
        self._logged_tags: set[int] = set()
        self._start_time = time.monotonic()

    def record_camera_frame(self) -> None:
        """Record one camera frame and update camera FPS."""
        self._camera_frame_count += 1
        now = time.monotonic()
        elapsed = now - self._camera_window_start

        if elapsed >= self.fps_window_sec:
            self.metrics.camera_fps = self._camera_frame_count / elapsed
            self._camera_frame_count = 0
            self._camera_window_start = now

    def record_detection_cycle(self) -> None:
        """Record one perception/detection update and update detection FPS."""
        self._detection_frame_count += 1
        now = time.monotonic()
        elapsed = now - self._detection_window_start

        if elapsed >= self.fps_window_sec:
            self.metrics.detection_fps = self._detection_frame_count / elapsed
            self._detection_frame_count = 0
            self._detection_window_start = now

    def record_tag_detection(self, tag_id: int | None) -> None:
        """
        Record the currently visible tag.

        Args:
            tag_id: Visible AprilTag ID, or None when no tag is visible.
        """
        self.metrics.current_tag_id = tag_id
        self._current_detection_time = time.monotonic()

        if tag_id is None:
            return

        self.metrics.tag_detection_counts[tag_id] = (
            self.metrics.tag_detection_counts.get(tag_id, 0) + 1
        )

        if tag_id not in self._logged_tags:
            self._logged_tags.add(tag_id)
            elapsed = self._current_detection_time - self._start_time
            print(f"Tag {tag_id} detected")
            print(f"Time: {elapsed:.2f} s")

    def record_navigation_state(self, state_name: str, action_name: str) -> None:
        """
        Store latest navigation state and action labels.

        Args:
            state_name: Current NavigationState name.
            action_name: Current command/action name.
        """
        self.metrics.navigation_state = state_name
        self.metrics.current_action = action_name

    def record_alignment_error(self, error_px: float | None) -> None:
        """
        Store the latest horizontal turn-tag alignment error.

        Args:
            error_px: Pixel error from image center, or None when unavailable.
        """
        self.metrics.alignment_error_px = error_px

    def record_command_generated(self, command: MotionCommand) -> None:
        """
        Record the time when a command was generated.

        Args:
            command: Command generated by navigation.
        """
        self._command_generated_time = time.monotonic()
        self.metrics.current_action = command.name

    def record_command_transmitted(self) -> None:
        """Record the time when the generated command was transmitted."""
        if self._current_detection_time is None:
            return

        transmitted_time = time.monotonic()
        self.metrics.command_latency_ms = (
            transmitted_time - self._current_detection_time
        ) * 1000.0

    def get_tag_count_text(self) -> str:
        """
        Return compact text showing per-tag frame counts.

        Returns:
            Human-readable tag count summary.
        """
        if not self.metrics.tag_detection_counts:
            return "Tag Counts: None"

        parts = [
            f"Tag {tag_id}: {count}"
            for tag_id, count in sorted(self.metrics.tag_detection_counts.items())
        ]
        return " | ".join(parts)
