import argparse
import time

import cv2

from communication.serial_motor_controller import SerialMotorController
from core.application_state import ApplicationState
from navigation.alignment_controller import AlignmentController
from navigation.motion_commands import MotionCommand
from navigation.navigation_state import NavigationState
from navigation.navigation_state_manager import NavigationStateManager
from perception.perception_manager import PerceptionManager
from validation.performance_monitor import PerformanceMonitor


def send_motion_command(
    serial_controller: SerialMotorController,
    command: MotionCommand,
    turn_right_value: float | None,
    use_calibrated_turn: bool = True,
) -> bool:
    """
    Send a navigation command, applying calibrated turn value when available.

    Args:
        serial_controller: Serial link to ESP32.
        command: Motion command generated by navigation.
        turn_right_value: Optional calibrated TURN_RIGHT value.
        use_calibrated_turn: True only for the route turn, not alignment nudges.

    Returns:
        True if the command was transmitted or already sent.
    """
    if (
        use_calibrated_turn
        and command == MotionCommand.TURN_RIGHT
        and turn_right_value is not None
    ):
        return serial_controller.send_command(
            command,
            value=turn_right_value,
            force=True,
        )

    return serial_controller.send_command(command)


def draw_metrics_overlay(frame, monitor: PerformanceMonitor) -> None:
    """
    Draw navigation validation metrics on the camera frame.

    Args:
        frame: Camera image to annotate.
        monitor: Performance monitor containing current metrics.
    """
    metrics = monitor.metrics
    latency_text = (
        f"{metrics.command_latency_ms:.1f} ms"
        if metrics.command_latency_ms is not None
        else "None"
    )
    alignment_text = (
        f"{metrics.alignment_error_px:.1f} px"
        if metrics.alignment_error_px is not None
        else "None"
    )

    lines = [
        f"Tag ID: {metrics.current_tag_id}",
        f"Camera FPS: {metrics.camera_fps:.1f}",
        f"Detection FPS: {metrics.detection_fps:.1f}",
        f"Navigation State: {metrics.navigation_state}",
        f"Current Action: {metrics.current_action}",
        f"Alignment Error: {alignment_text}",
        f"Command Latency: {latency_text}",
        monitor.get_tag_count_text(),
    ]

    y = 30
    for line in lines:
        cv2.putText(
            frame,
            line,
            (20, y),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.65,
            (255, 255, 255),
            2,
        )
        y += 28


def main() -> None:
    """Run live navigation validation with camera overlay and serial commands."""
    args = parse_args()
    application_state = ApplicationState()
    perception_manager = PerceptionManager(application_state)
    navigation_manager = NavigationStateManager()
    alignment_controller = AlignmentController(
        center_tolerance_px=args.alignment_tolerance,
    )
    serial_controller = SerialMotorController(
        port=args.port,
        baudrate=args.baudrate,
    )
    monitor = PerformanceMonitor()
    stop_time: float | None = None
    last_alignment_command: MotionCommand | None = None
    last_alignment_command_time = 0.0
    stop_to_turn_delay_sec = args.stop_to_turn_delay

    if not perception_manager.initialize():
        print("PerceptionManager failed to initialize camera.")
        return

    if not serial_controller.connect():
        perception_manager.release()
        return

    try:
        while True:
            monitor.record_camera_frame()
            perception_manager.update()
            monitor.record_detection_cycle()

            frame = perception_manager.last_frame
            perception = application_state.perception
            tag_id = perception.tag_id if perception.tag_visible else None
            monitor.record_tag_detection(tag_id)

            key = cv2.waitKey(1) & 0xFF
            start_pressed = key == ord("f") or key == ord("F")

            motion_complete = False
            if navigation_manager.state == NavigationState.TURNING:
                if navigation_manager.stop_before_turn_sent and not navigation_manager.turn_right_sent:
                    if stop_time is None:
                        stop_time = time.monotonic()

                    motion_complete = (
                        time.monotonic() - stop_time
                    ) >= stop_to_turn_delay_sec
                else:
                    stop_time = None
            else:
                stop_time = None

            alignment_error: float | None = None
            alignment_complete = False
            alignment_command: MotionCommand | None = None
            turn_tag_visible = tag_id == 3

            if navigation_manager.state == NavigationState.ALIGNING:
                if turn_tag_visible and frame is not None and perception.center_x is not None:
                    alignment_result = alignment_controller.calculate(
                        image_width=frame.shape[1],
                        tag_center_x=perception.center_x,
                    )
                    alignment_error = alignment_result.error_x
                    alignment_complete = (
                        abs(alignment_error) <= args.alignment_tolerance
                    )
                    print(f"Alignment Error: {alignment_error:.1f}")

                    if not alignment_complete:
                        alignment_command = alignment_result.action
                else:
                    alignment_command = MotionCommand.STOP

            monitor.record_alignment_error(alignment_error)

            command = navigation_manager.update(
                tag_id=tag_id,
                start_pressed=start_pressed,
                motion_complete=motion_complete,
                alignment_complete=alignment_complete,
                tag_visible=turn_tag_visible,
            )

            action_name = (
                navigation_manager.current_action.name
                if navigation_manager.current_action is not None
                else "None"
            )
            monitor.record_navigation_state(
                navigation_manager.state.name,
                action_name,
            )

            if command is not None:
                last_alignment_command = None
                monitor.record_command_generated(command)
                send_motion_command(
                    serial_controller,
                    command,
                    args.turn_right_value,
                    use_calibrated_turn=True,
                )
                monitor.record_command_transmitted()
            elif alignment_command is not None:
                monitor.metrics.current_action = alignment_command.name
                now = time.monotonic()
                alignment_due = (
                    alignment_command != last_alignment_command
                    or (now - last_alignment_command_time)
                    >= args.alignment_command_interval
                )

                if alignment_due:
                    send_motion_command(
                        serial_controller,
                        alignment_command,
                        args.turn_right_value,
                        use_calibrated_turn=False,
                    )
                    last_alignment_command = alignment_command
                    last_alignment_command_time = now

            if frame is not None:
                draw_metrics_overlay(frame, monitor)
                cv2.imshow("AGV Navigation Performance", frame)

            if key == ord("q"):
                break
    except KeyboardInterrupt:
        print("Stopping navigation validation.")
    finally:
        serial_controller.send_command(MotionCommand.STOP)
        serial_controller.disconnect()
        perception_manager.release()
        cv2.destroyAllWindows()


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments for route completion validation."""
    parser = argparse.ArgumentParser(
        description="Run navigation metrics and route completion validation.",
    )
    parser.add_argument("--port", default="/dev/ttyUSB0")
    parser.add_argument("--baudrate", type=int, default=115200)
    parser.add_argument(
        "--turn-right-value",
        type=float,
        default=50.0,
        help="Calibrated value sent as TURN_RIGHT <value> at Tag 3.",
    )
    parser.add_argument(
        "--alignment-tolerance",
        type=float,
        default=10.0,
        help="Maximum Tag 3 horizontal error before stopping for the turn.",
    )
    parser.add_argument(
        "--alignment-command-interval",
        type=float,
        default=0.5,
        help="Seconds between repeated alignment correction commands.",
    )
    parser.add_argument(
        "--stop-to-turn-delay",
        type=float,
        default=0.5,
        help="Seconds to wait after STOP before sending TURN_RIGHT.",
    )
    return parser.parse_args()


if __name__ == "__main__":
    main()
